export enum FanRangeValues {
  MIN_TEMP = 0,
  MAX_TEMP = 50,
  MIN_PERCENTAGE = 0,
  MAX_PERCENTAGE = 100,
  MIN_DIRECTION = 0,
  MAX_DIRECTION = 255,
  DEFAULT_TEMP = 23,
  DEFAULT_PERCENTAGE = 40,
  DEFAULT_DIRECTION = 100,
}
